lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    # Configuration des extracteurs de token
    token_extractors:
        cookie:
            enabled: true
            name: BEARER
    # ...
    set_cookies:
        BEARER: ~
