vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    recipe_images:
      uri_prefix: /uploads/recipes
      upload_destination: '%kernel.project_dir%/public/uploads/recipes'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

