vich_uploader:
  db_driver: orm
  metadata:
      type: attribute
  mappings:
      recipe_images:
          uri_prefix: /uploads/recipes
          upload_destination: recipe_images_storage
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
